source 'https://rubygems.org'

group :octopress do
  gem "octopress"
  gem "octopress-solarized", path: "../"
  gem "octopress-ink"
  gem "octopress-code-highlighter"
  gem "octopress-codefence"
end

gem "pry-debugger"
